/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface Transaction {
  id: string;
  datetime: string; // ISO 8601 string, e.g., "2026-05-22T14:30:00.000Z"
  amount: number; // Always positive. The absolute amount of currency.
  type: 'income' | 'expense';
  category: string; // Main category, e.g., "餐飲", "交通"
  subcategory: string; // Subcategory, e.g., "早餐", "捷運"
  note: string;
  isRecurring?: boolean; // Automatically generated by recurring rules
  recurringRuleId?: string;
}

export interface RecurringRule {
  id: string;
  name: string; // E.g., "Netflix 訂閱"
  amount: number; // Positive absolute amount
  type: 'income' | 'expense';
  category: string;
  subcategory: string;
  dayOfMonth: number; // 1 to 31
  isActive: boolean;
  lastTriggeredMonth?: string; // e.g., "2026-05" - prevents duplicate firing in the same month
  note: string;
}

export interface Debt {
  id: string;
  debtorName: string; // Name of person who owes money
  debtorEmail: string; // Optional email of debtor for sending reminders
  amount: number; // Amount owed (positive number)
  description: string; // Detail or description of the debt
  datetime: string; // Date when debt was created
  isPaid: boolean; // Repayment status
  paidDatetime?: string; // Repay date
  reminderSentCount?: number; // Count of Gmail reminders sent
  lastReminderSentAt?: string; // Timestamp of the last reminder
}

export interface CategoryStructure {
  name: string;
  icon: string; // lucide icon name
  subcategories: string[];
}

export const MAIN_CATEGORIES: CategoryStructure[] = [
  {
    name: '餐飲',
    icon: 'Utensils',
    subcategories: ['早餐', '午餐', '晚餐', '飲料', '點心', '其他餐飲']
  },
  {
    name: '交通',
    icon: 'Car',
    subcategories: ['捷運/地鐵', '公車/客運', '計程車/計程車', '加油/燃料', '停車費', '機車', '火車/高鐵', '其他交通']
  },
  {
    name: '娛樂',
    icon: 'Gamepad2',
    subcategories: ['電影', '遊戲', 'KTV/音樂', '旅遊/住宿', '書籍', '運動慢跑', '玩具公仔', '其他娛樂']
  },
  {
    name: '居家',
    icon: 'Home',
    subcategories: ['房租', '房貸', '水電瓦斯', '日常用品', '家具/電器', '修繕', '管理費', '其他居家']
  },
  {
    name: '醫療',
    icon: 'HeartPulse',
    subcategories: ['診所掛號', '藥品/日常保健', '住院醫療', '牙醫/整建', '其他醫療']
  },
  {
    name: '數位服務',
    icon: 'Cloud',
    subcategories: ['串流音樂(Spotify/Apple)', '串流影音(Netflix/Disney+)', '雲端空間(iCloud/Google)', '軟體訂閱', '寬頻/電信費', '其他數位']
  },
  {
    name: '其他支出',
    icon: 'Tag',
    subcategories: ['購物轉帳', '服飾配件', '人情禮金', '保險費', '捐款/慈善', '其他雜項']
  },
  {
    name: '收入項目',
    icon: 'TrendingUp',
    subcategories: ['薪資', '獎金', '利息收益', '投資分紅', '二手轉售', '零用錢', '政府補助', '其他收入']
  }
];

export interface iOSWidgetConfig {
  size: 'small' | 'medium';
  theme: 'dark' | 'light' | 'mono';
  showQuickButtons: boolean;
  type: 'balance' | 'charts' | 'recent';
}

export interface FrequentDebtor {
  id: string;
  name: string;
  email: string;
}

